### PR TITLE
Added Kelly record

### PR DESCRIPTION
**Pull request by Osoba001**

### CODE REVIEW

**Review by Adexandria — APPROVED** [review]

**Review by giddy11 — CHANGES_REQUESTED** [review]
**could u please explain the format of what is in the kelly.cs using comments**. thanks @Osoba001

**Review by giddy11 — APPROVED** [review]
nice one

**Comment by giddy11** [comment]
> 

Oooh... Thanks

**Comment by Osoba001** [comment]
Conclusion

**Pull request closed without merging**
